# syntax=docker/dockerfile:1
FROM python:3.11-slim as builder

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /build

COPY pyproject.toml ./

# RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR
RUN poetry install --no-root && rm -rf $POETRY_CACHE_DIR

FROM python:3.11-slim as runtime

WORKDIR /app

# 從建置階段複製已安裝的依賴
COPY --from=builder /build/.venv /build/.venv
ENV PATH="/build/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

# 從建置階段複製應用程式原始碼
COPY . /app

EXPOSE 8501

# HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "streamlit_app.py"]