# syntax=docker/dockerfile:1
FROM python:3.11-slim

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=0 \
    POETRY_VIRTUALENVS_CREATE=0 \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    PYTHONDONTWRITEBYTECODE=1 \ 
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY . /app

# RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR
RUN poetry install

EXPOSE 8000


ENTRYPOINT ["adk", "web"]